// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-causes.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var CAUSES = [
  { slug: "education-equality", title: "Education Equality & Access for Every Child", category: "Education", raised: 4e4, goal: 65200, location: "Wakiso & Mukono districts, Uganda", beneficiaries: "1,200+ children" },
  { slug: "healthcare-access", title: "Healthcare Access for Vulnerable Communities", category: "Emergency Health Relief", raised: 16800, goal: 4e4, location: "Greater Kampala outskirts", beneficiaries: "8,500+ patients yearly" },
  { slug: "nutritional-support", title: "Nutritional Support & Food Security", category: "Food Security", raised: 60800, goal: 1e5, location: "Kampala & Lake Victoria region", beneficiaries: "2,400 families" },
  { slug: "clean-water", title: "Access to Clean Water for All", category: "Water Purification", raised: 20800, goal: 6e4, location: "Northern Uganda", beneficiaries: "18 villages" },
  { slug: "women-girls", title: "Empowering Women and Girls Through Education", category: "Empowerment", raised: 8e4, goal: 85e3, location: "Kampala & Jinja", beneficiaries: "640 young women" }
];
var list_causes_default = defineTool({
  name: "list_causes",
  title: "List causes",
  description: "List the charitable causes Arsenal Fund Uganda currently supports, with fundraising progress and location.",
  inputSchema: {
    category: z.string().optional().describe("Optional case-insensitive category filter (e.g. Education, Food Security).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category }) => {
    const items = category ? CAUSES.filter((c) => c.category.toLowerCase().includes(category.toLowerCase())) : CAUSES;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { causes: items }
    };
  }
});

// src/lib/mcp/tools/list-programs.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
var PROGRAMS = [
  { slug: "back-to-school", title: "Back-to-School Scholar Program", category: "Long-Term Education", status: "Active", participants: 1240, startedYear: 2016 },
  { slug: "mobile-health-clinics", title: "Mobile Health Clinics on Wheels", category: "Healthcare Outreach", status: "Expanding", participants: 8500, startedYear: 2019 },
  { slug: "community-kitchens", title: "Community Kitchens & Nutrition", category: "Food Security", status: "Active", participants: 2400, startedYear: 2018 },
  { slug: "girls-rising", title: "Girls Rising Leadership Academy", category: "Women & Girls Empowerment", status: "Active", participants: 640, startedYear: 2020 },
  { slug: "safe-water-wells", title: "Safe Water Wells & Hygiene Education", category: "Clean Water Infrastructure", status: "Expanding", participants: 9e3, startedYear: 2017 },
  { slug: "creative-arts-studios", title: "Creative Arts After-School Studios", category: "Youth & Creativity", status: "New", participants: 320, startedYear: 2023 }
];
var list_programs_default = defineTool2({
  name: "list_programs",
  title: "List programs",
  description: "List the active programs run by Arsenal Fund Uganda, including status and number of participants.",
  inputSchema: {
    status: z2.string().optional().describe("Optional filter on status (e.g. Active, Expanding, New).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ status }) => {
    const items = status ? PROGRAMS.filter((p) => p.status.toLowerCase() === status.toLowerCase()) : PROGRAMS;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { programs: items }
    };
  }
});

// src/lib/mcp/tools/get-contact-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var get_contact_info_default = defineTool3({
  name: "get_contact_info",
  title: "Get contact info",
  description: "Return public contact details for Arsenal Fund Uganda: phone, WhatsApp, email, address, and donation link.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      organization: "Arsenal Fund Uganda",
      founded: 2025,
      phone_local: "0731234815",
      phone_international: "+256731234815",
      whatsapp: "https://wa.me/256731234815",
      email: "hello@arsenalfunduganda.org",
      address: "Kampala, Uganda",
      donate_url: "https://wa.me/256731234815?text=" + encodeURIComponent("Hello Arsenal Fund Uganda \u{1F44B} I'd love to make a donation and support the cause. Please share the next steps.")
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-sponsor-tiers.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
var TIERS = [
  { name: "Spark", price_usd: 120, description: "Sponsor essentials for one child for a school term.", perks: ["Monthly progress updates", "Personal thank-you letter", "Impact certificate"] },
  { name: "Hope", price_usd: 280, description: "Full sponsorship for a child including meals, tuition and materials.", perks: ["Quarterly video updates", "Two personal letters/year", "Named on donor wall", "Annual report"] },
  { name: "Legacy", price_usd: 550, description: "Deep partnership funding a child plus community program contribution.", perks: ["Direct mentor pairing", "Site visit invitation", "Recognition plaque", "Full transparency dashboard"] }
];
var list_sponsor_tiers_default = defineTool4({
  name: "list_sponsor_tiers",
  title: "List sponsor tiers",
  description: "Return the sponsorship tiers (Spark, Hope, Legacy) with prices in USD and included perks.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(TIERS, null, 2) }],
    structuredContent: { tiers: TIERS }
  })
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "arsenal-fund-uganda-mcp",
  title: "Arsenal Fund Uganda MCP",
  version: "0.1.0",
  instructions: "Public tools for Arsenal Fund Uganda \u2014 a Uganda-based charity founded by Arsenal FC supporters. Use `list_causes` and `list_programs` to explore the initiatives, `list_sponsor_tiers` for sponsorship options, and `get_contact_info` for how to donate or reach the team.",
  tools: [list_causes_default, list_programs_default, list_sponsor_tiers_default, get_contact_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
